[BaseOperationCost]
    StorePerByte    = 10
    DataCopyPerByte = 10
    CompilePerByte  = 10
    PersitPerByte   = 10
    ReleasePerByte  = 10

[ElrondAPICost]
    GetOwner           = 10
    GetExternalBalance = 10
    GetBlockHash       = 10
    TransferValue      = 10
    GetArgument        = 10
    GetFunction        = 10
    GetNumArguments    = 10
    StorageStore       = 10
    StorageLoad        = 10
    GetCaller          = 10
    GetCallValue       = 10
    Log                = 10
    Finish             = 10
    SignalError        = 10
    GetBlockTimeStamp  = 10
    GetGasLeft         = 10
    Int64GetArgument   = 10
    Int64StorageStore  = 10
    Int64StorageLoad   = 10
    Int64Finish        = 10
    GetStateRootHash   = 10
    GetBlockNonce      = 10
    GetBlockEpoch      = 10
    GetBlockRound      = 10
    GetBlockRandomSeed = 10
    ExecuteOnSameContext = 10
    ExecuteOnDestContext = 10
    DelegateExecution    = 10
    ExecuteReadOnly      = 10
    AsyncCallStep        = 10
    AsyncCallbackGasLock = 10
    CreateContract       = 10
    GetReturnData        = 10
    GetNumReturnData     = 10
    GetReturnDataSize    = 10

[EthAPICost]
    UseGas              = 10
    GetAddress          = 10
    GetExternalBalance  = 10
    GetBlockHash        = 10
    Call                = 10
    CallDataCopy        = 10
    GetCallDataSize     = 10
    CallCode            = 10
    CallDelegate        = 10
    CallStatic          = 10
    StorageStore        = 10
    StorageLoad         = 10
    GetCaller           = 10
    GetCallValue        = 10
    CodeCopy            = 10
    GetCodeSize         = 10
    GetBlockCoinbase    = 10
    Create              = 10
    GetBlockDifficulty  = 10
    ExternalCodeCopy    = 10
    GetExternalCodeSize = 10
    GetGasLeft          = 10
    GetBlockGasLimit    = 10
    GetTxGasPrice       = 10
    Log                 = 10
    GetBlockNumber      = 10
    GetTxOrigin         = 10
    Finish              = 10
    Revert              = 10
    GetReturnDataSize   = 10
    ReturnDataCopy      = 10
    SelfDestruct        = 10
    GetBlockTimeStamp   = 10

[BigIntAPICost]
    BigIntNew                = 10
    BigIntByteLength         = 10
    BigIntGetBytes           = 10
    BigIntSetBytes           = 10
    BigIntIsInt64            = 10
    BigIntGetInt64           = 10
    BigIntSetInt64           = 10
    BigIntAdd                = 10
    BigIntSub                = 10
    BigIntMul                = 10
    BigIntCmp                = 10
    BigIntFinish             = 10
    BigIntStorageLoad        = 10
    BigIntStorageStore       = 10
    BigIntGetArgument        = 10
    BigIntGetCallValue       = 10
    BigIntGetExternalBalance = 10

[CryptoAPICost]
    SHA256    = 10
    Keccak256 = 10

[WASMOpcodeCost]
    Unreachable = 1
    Nop = 1
    Block = 1
    Loop = 1
    If = 1
    Else = 1
    End = 1
    Br = 1
    BrIf = 1
    BrTable = 1
    Return = 1
    Call = 1
    CallIndirect = 1
    Drop = 1
    Select = 1
    TypedSelect = 1
    LocalGet = 1
    LocalSet = 1
    LocalTee = 1
    GlobalGet = 1
    GlobalSet = 1
    I32Load = 1
    I64Load = 1
    F32Load = 1
    F64Load = 1
    I32Load8S = 1
    I32Load8U = 1
    I32Load16S = 1
    I32Load16U = 1
    I64Load8S = 1
    I64Load8U = 1
    I64Load16S = 1
    I64Load16U = 1
    I64Load32S = 1
    I64Load32U = 1
    I32Store = 1
    I64Store = 1
    F32Store = 1
    F64Store = 1
    I32Store8 = 1
    I32Store16 = 1
    I64Store8 = 1
    I64Store16 = 1
    I64Store32 = 1
    MemorySize = 1
    MemoryGrow = 1
    I32Const = 1
    I64Const = 1
    F32Const = 1
    F64Const = 1
    RefNull = 1
    RefIsNull = 1
    RefFunc = 1
    I32Eqz = 1
    I32Eq = 1
    I32Ne = 1
    I32LtS = 1
    I32LtU = 1
    I32GtS = 1
    I32GtU = 1
    I32LeS = 1
    I32LeU = 1
    I32GeS = 1
    I32GeU = 1
    I64Eqz = 1
    I64Eq = 1
    I64Ne = 1
    I64LtS = 1
    I64LtU = 1
    I64GtS = 1
    I64GtU = 1
    I64LeS = 1
    I64LeU = 1
    I64GeS = 1
    I64GeU = 1
    F32Eq = 1
    F32Ne = 1
    F32Lt = 1
    F32Gt = 1
    F32Le = 1
    F32Ge = 1
    F64Eq = 1
    F64Ne = 1
    F64Lt = 1
    F64Gt = 1
    F64Le = 1
    F64Ge = 1
    I32Clz = 1
    I32Ctz = 1
    I32Popcnt = 1
    I32Add = 1
    I32Sub = 1
    I32Mul = 1
    I32DivS = 1
    I32DivU = 1
    I32RemS = 1
    I32RemU = 1
    I32And = 1
    I32Or = 1
    I32Xor = 1
    I32Shl = 1
    I32ShrS = 1
    I32ShrU = 1
    I32Rotl = 1
    I32Rotr = 1
    I64Clz = 1
    I64Ctz = 1
    I64Popcnt = 1
    I64Add = 1
    I64Sub = 1
    I64Mul = 1
    I64DivS = 1
    I64DivU = 1
    I64RemS = 1
    I64RemU = 1
    I64And = 1
    I64Or = 1
    I64Xor = 1
    I64Shl = 1
    I64ShrS = 1
    I64ShrU = 1
    I64Rotl = 1
    I64Rotr = 1
    F32Abs = 1
    F32Neg = 1
    F32Ceil = 1
    F32Floor = 1
    F32Trunc = 1
    F32Nearest = 1
    F32Sqrt = 1
    F32Add = 1
    F32Sub = 1
    F32Mul = 1
    F32Div = 1
    F32Min = 1
    F32Max = 1
    F32Copysign = 1
    F64Abs = 1
    F64Neg = 1
    F64Ceil = 1
    F64Floor = 1
    F64Trunc = 1
    F64Nearest = 1
    F64Sqrt = 1
    F64Add = 1
    F64Sub = 1
    F64Mul = 1
    F64Div = 1
    F64Min = 1
    F64Max = 1
    F64Copysign = 1
    I32WrapI64 = 1
    I32TruncF33S = 1
    I32TruncF33U = 1
    I32TruncF65S = 1
    I32TruncF65U = 1
    I64ExtendI33S = 1
    I64ExtendI33U = 1
    I64TruncF33S = 1
    I64TruncF33U = 1
    I64TruncF65S = 1
    I64TruncF65U = 1
    F32ConvertI33S = 1
    F32ConvertI33U = 1
    F32ConvertI65S = 1
    F32ConvertI65U = 1
    F32DemoteF65 = 1
    F64ConvertI33S = 1
    F64ConvertI33U = 1
    F64ConvertI65S = 1
    F64ConvertI65U = 1
    F64PromoteF33 = 1
    I32ReinterpretF33 = 1
    I64ReinterpretF65 = 1
    F32ReinterpretI33 = 1
    F64ReinterpretI65 = 1
    I32Extend8S = 1
    I32Extend17S = 1
    I64Extend8S = 1
    I64Extend17S = 1
    I64Extend33S = 1
    I32TruncSatF33S = 1
    I32TruncSatF33U = 1
    I32TruncSatF65S = 1
    I32TruncSatF65U = 1
    I64TruncSatF33S = 1
    I64TruncSatF33U = 1
    I64TruncSatF65S = 1
    I64TruncSatF65U = 1
    MemoryInit = 1
    DataDrop = 1
    MemoryCopy = 1
    MemoryFill = 1
    TableInit = 1
    ElemDrop = 1
    TableCopy = 1
    TableFill = 1
    TableGet = 1
    TableSet = 1
    TableGrow = 1
    TableSize = 1
    AtomicNotify = 1
    I32AtomicWait = 1
    I64AtomicWait = 1
    AtomicFence = 1
    I32AtomicLoad = 1
    I64AtomicLoad = 1
    I32AtomicLoad9U = 1
    I32AtomicLoad17U = 1
    I64AtomicLoad9U = 1
    I64AtomicLoad17U = 1
    I64AtomicLoad33U = 1
    I32AtomicStore = 1
    I64AtomicStore = 1
    I32AtomicStore9 = 1
    I32AtomicStore17 = 1
    I64AtomicStore9 = 1
    I64AtomicStore17 = 1
    I64AtomicStore33 = 1
    I32AtomicRmwAdd = 1
    I64AtomicRmwAdd = 1
    I32AtomicRmw9AddU = 1
    I32AtomicRmw17AddU = 1
    I64AtomicRmw9AddU = 1
    I64AtomicRmw17AddU = 1
    I64AtomicRmw33AddU = 1
    I32AtomicRmwSub = 1
    I64AtomicRmwSub = 1
    I32AtomicRmw9SubU = 1
    I32AtomicRmw17SubU = 1
    I64AtomicRmw9SubU = 1
    I64AtomicRmw17SubU = 1
    I64AtomicRmw33SubU = 1
    I32AtomicRmwAnd = 1
    I64AtomicRmwAnd = 1
    I32AtomicRmw9AndU = 1
    I32AtomicRmw17AndU = 1
    I64AtomicRmw9AndU = 1
    I64AtomicRmw17AndU = 1
    I64AtomicRmw33AndU = 1
    I32AtomicRmwOr = 1
    I64AtomicRmwOr = 1
    I32AtomicRmw9OrU = 1
    I32AtomicRmw17OrU = 1
    I64AtomicRmw9OrU = 1
    I64AtomicRmw17OrU = 1
    I64AtomicRmw33OrU = 1
    I32AtomicRmwXor = 1
    I64AtomicRmwXor = 1
    I32AtomicRmw9XorU = 1
    I32AtomicRmw17XorU = 1
    I64AtomicRmw9XorU = 1
    I64AtomicRmw17XorU = 1
    I64AtomicRmw33XorU = 1
    I32AtomicRmwXchg = 1
    I64AtomicRmwXchg = 1
    I32AtomicRmw9XchgU = 1
    I32AtomicRmw17XchgU = 1
    I64AtomicRmw9XchgU = 1
    I64AtomicRmw17XchgU = 1
    I64AtomicRmw33XchgU = 1
    I32AtomicRmwCmpxchg = 1
    I64AtomicRmwCmpxchg = 1
    I32AtomicRmw9CmpxchgU = 1
    I32AtomicRmw17CmpxchgU = 1
    I64AtomicRmw9CmpxchgU = 1
    I64AtomicRmw17CmpxchgU = 1
    I64AtomicRmw33CmpxchgU = 1
    V128Load = 1
    V128Store = 1
    V128Const = 1
    I8x16Splat = 1
    I8x16ExtractLaneS = 1
    I8x16ExtractLaneU = 1
    I8x16ReplaceLane = 1
    I16x8Splat = 1
    I16x8ExtractLaneS = 1
    I16x8ExtractLaneU = 1
    I16x8ReplaceLane = 1
    I32x4Splat = 1
    I32x4ExtractLane = 1
    I32x4ReplaceLane = 1
    I64x2Splat = 1
    I64x2ExtractLane = 1
    I64x2ReplaceLane = 1
    F32x4Splat = 1
    F32x4ExtractLane = 1
    F32x4ReplaceLane = 1
    F64x2Splat = 1
    F64x2ExtractLane = 1
    F64x2ReplaceLane = 1
    I8x16Eq = 1
    I8x16Ne = 1
    I8x16LtS = 1
    I8x16LtU = 1
    I8x16GtS = 1
    I8x16GtU = 1
    I8x16LeS = 1
    I8x16LeU = 1
    I8x16GeS = 1
    I8x16GeU = 1
    I16x8Eq = 1
    I16x8Ne = 1
    I16x8LtS = 1
    I16x8LtU = 1
    I16x8GtS = 1
    I16x8GtU = 1
    I16x8LeS = 1
    I16x8LeU = 1
    I16x8GeS = 1
    I16x8GeU = 1
    I32x4Eq = 1
    I32x4Ne = 1
    I32x4LtS = 1
    I32x4LtU = 1
    I32x4GtS = 1
    I32x4GtU = 1
    I32x4LeS = 1
    I32x4LeU = 1
    I32x4GeS = 1
    I32x4GeU = 1
    F32x4Eq = 1
    F32x4Ne = 1
    F32x4Lt = 1
    F32x4Gt = 1
    F32x4Le = 1
    F32x4Ge = 1
    F64x2Eq = 1
    F64x2Ne = 1
    F64x2Lt = 1
    F64x2Gt = 1
    F64x2Le = 1
    F64x2Ge = 1
    V128Not = 1
    V128And = 1
    V128AndNot = 1
    V128Or = 1
    V128Xor = 1
    V128Bitselect = 1
    I8x16Neg = 1
    I8x16AnyTrue = 1
    I8x16AllTrue = 1
    I8x16Shl = 1
    I8x16ShrS = 1
    I8x16ShrU = 1
    I8x16Add = 1
    I8x16AddSaturateS = 1
    I8x16AddSaturateU = 1
    I8x16Sub = 1
    I8x16SubSaturateS = 1
    I8x16SubSaturateU = 1
    I8x16MinS = 1
    I8x16MinU = 1
    I8x16MaxS = 1
    I8x16MaxU = 1
    I8x16Mul = 1
    I16x8Neg = 1
    I16x8AnyTrue = 1
    I16x8AllTrue = 1
    I16x8Shl = 1
    I16x8ShrS = 1
    I16x8ShrU = 1
    I16x8Add = 1
    I16x8AddSaturateS = 1
    I16x8AddSaturateU = 1
    I16x8Sub = 1
    I16x8SubSaturateS = 1
    I16x8SubSaturateU = 1
    I16x8Mul = 1
    I16x8MinS = 1
    I16x8MinU = 1
    I16x8MaxS = 1
    I16x8MaxU = 1
    I32x4Neg = 1
    I32x4AnyTrue = 1
    I32x4AllTrue = 1
    I32x4Shl = 1
    I32x4ShrS = 1
    I32x4ShrU = 1
    I32x4Add = 1
    I32x4Sub = 1
    I32x4Mul = 1
    I32x4MinS = 1
    I32x4MinU = 1
    I32x4MaxS = 1
    I32x4MaxU = 1
    I64x2Neg = 1
    I64x2AnyTrue = 1
    I64x2AllTrue = 1
    I64x2Shl = 1
    I64x2ShrS = 1
    I64x2ShrU = 1
    I64x2Add = 1
    I64x2Sub = 1
    I64x2Mul = 1
    F32x4Abs = 1
    F32x4Neg = 1
    F32x4Sqrt = 1
    F32x4Add = 1
    F32x4Sub = 1
    F32x4Mul = 1
    F32x4Div = 1
    F32x4Min = 1
    F32x4Max = 1
    F64x2Abs = 1
    F64x2Neg = 1
    F64x2Sqrt = 1
    F64x2Add = 1
    F64x2Sub = 1
    F64x2Mul = 1
    F64x2Div = 1
    F64x2Min = 1
    F64x2Max = 1
    I32x4TruncSatF33x4S = 1
    I32x4TruncSatF33x4U = 1
    I64x2TruncSatF65x2S = 1
    I64x2TruncSatF65x2U = 1
    F32x4ConvertI33x4S = 1
    F32x4ConvertI33x4U = 1
    F64x2ConvertI65x2S = 1
    F64x2ConvertI65x2U = 1
    V8x16Swizzle = 1
    V8x16Shuffle = 1
    V8x16LoadSplat = 1
    V16x8LoadSplat = 1
    V32x4LoadSplat = 1
    V64x2LoadSplat = 1
    I8x16NarrowI17x8S = 1
    I8x16NarrowI17x8U = 1
    I16x8NarrowI33x4S = 1
    I16x8NarrowI33x4U = 1
    I16x8WidenLowI9x16S = 1
    I16x8WidenHighI9x16S = 1
    I16x8WidenLowI9x16U = 1
    I16x8WidenHighI9x16U = 1
    I32x4WidenLowI17x8S = 1
    I32x4WidenHighI17x8S = 1
    I32x4WidenLowI17x8U = 1
    I32x4WidenHighI17x8U = 1
    I16x8Load8x9S = 1
    I16x8Load8x9U = 1
    I32x4Load17x4S = 1
    I32x4Load17x4U = 1
    I64x2Load33x2S = 1
    I64x2Load33x2U = 1
    I8x16RoundingAverageU = 1
    I16x8RoundingAverageU = 1
