[BaseOperationCost]
    StorePerByte    = 10
    DataCopyPerByte = 10

[ElrondAPICost]
    GetOwner           = 10
    GetExternalBalance = 10
    GetBlockHash       = 10
    TransferValue      = 10
    GetArgument        = 10
    GetFunction        = 10
    GetNumArguments    = 10
    StorageStore       = 10
    StorageLoad        = 10
    GetCaller          = 10
    GetCallValue       = 10
    Log                = 10
    Finish             = 10
    SignalError        = 10
    GetBlockTimeStamp  = 10
    GetGasLeft         = 10
    Int64GetArgument   = 10
    Int64StorageStore  = 10
    Int64StorageLoad   = 10
    Int64Finish        = 10

[EthAPICost]
    UseGas              = 10
    GetAddress          = 10
    GetExternalBalance  = 10
    GetBlockHash        = 10
    Call                = 10
    CallDataCopy        = 10
    GetCallDataSize     = 10
    CallCode            = 10
    CallDelegate        = 10
    CallStatic          = 10
    StorageStore        = 10
    StorageLoad         = 10
    GetCaller           = 10
    GetCallValue        = 10
    CodeCopy            = 10
    GetCodeSize         = 10
    GetBlockCoinbase    = 10
    Create              = 10
    GetBlockDifficulty  = 10
    ExternalCodeCopy    = 10
    GetExternalCodeSize = 10
    GetGasLeft          = 10
    GetBlockGasLimit    = 10
    GetTxGasPrice       = 10
    Log                 = 10
    GetBlockNumber      = 10
    GetTxOrigin         = 10
    Finish              = 10
    Revert              = 10
    GetReturnDataSize   = 10
    ReturnDataCopy      = 10
    SelfDestruct        = 10
    GetBlockTimeStamp   = 10

[BigIntAPICost]
    BigIntNew                = 10
    BigIntByteLength         = 10
    BigIntGetBytes           = 10
    BigIntSetBytes           = 10
    BigIntIsInt64            = 10
    BigIntGetInt64           = 10
    BigIntSetInt64           = 10
    BigIntAdd                = 10
    BigIntSub                = 10
    BigIntMul                = 10
    BigIntCmp                = 10
    BigIntFinish             = 10
    BigIntStorageLoad        = 10
    BigIntStorageStore       = 10
    BigIntGetArgument        = 10
    BigIntGetCallValue       = 10
    BigIntGetExternalBalance = 10

[CryptoAPICost]
    SHA256    = 10
    Keccak256 = 10